name: Update readme file

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v2
      - uses: Readme-Workflows/recent-activity@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://sergeypanteleev.com/en/feed,https://sergeypanteleev.com/ru/feed"